baseURL = 'https://sambelltacq.github.io/d-tacq.co.uk/'
languageCode = 'en-gb'
title = 'D-tacq Solutions'
theme = "d-tacq_theme"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
