baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'D-tacq Solutions '
#theme = "mainroad"
theme = "d-tacq_theme"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
